db:
  image: postgres:13.10
  env_file: .env
  volumes:
    - pg_data:/var/lib/postgresql/data

backend:
  build: ./backend/
  env_file: .env
  ports:
    - "8001:8000"
  links:
    - db
  volumes:
    - backend_static:/app/staticfiles

frontend:
  build: ./frontend/
  env_file: .env
  ports:
    - "3000:3000"
  links:
    - backend
  volumes:
    - frontend_static:/app/staticfiles

gateway:
  build: ./gateway/
  volumes:
    - static_volume:/static
  ports:
    - "8000:80"